### ISSUE TITLE
errororrorr

### ISSUE THREAD

**Issue by enjoy301** [sesaram/ai_hackathon#4]
### from
```
img = Image.open('example.jpg')
```
### to
```python
b = BytesIO()
Image.fromarray(cv2.imread("example.jpg")).save(b, format="jpeg")
img_cv2 = Image.open(b)
```
### and type is 일치
`
<class 'PIL.JpegImagePlugin.JpegImageFile'>,  <class 'PIL.JpegImagePlugin.JpegImageFile'>
`

### error message
```
Traceback (most recent call last):
  File "C:\Users\eunjo\OneDrive\바탕 화면\project\deep\venv\lib\site-packages\pandas\core\indexes\base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2131, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2140, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\eunjo\OneDrive\바탕 화면\project\deep\ai_hackathon\detector\example.py", line 17, in <module>
    result = makePersonBox(results)
  File "C:\Users\eunjo\OneDrive\바탕 화면\project\deep\ai_hackathon\detector\yolov5\preproc.py", line 7, in makePersonBox
    l = results.loc[i]
  File "C:\Users\eunjo\OneDrive\바탕 화면\project\deep\venv\lib\site-packages\pandas\core\indexing.py", line 931, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "C:\Users\eunjo\OneDrive\바탕 화면\project\deep\venv\lib\site-packages\pandas\core\indexing.py", line 1164, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "C:\Users\eunjo\OneDrive\바탕 화면\project\deep\venv\lib\site-packages\pandas\core\indexing.py", line 1113, in _get_label
    return self.obj.xs(label, axis=axis)
  File "C:\Users\eunjo\OneDrive\바탕 화면\project\deep\venv\lib\site-packages\pandas\core\generic.py", line 3776, in xs
    loc = index.get_loc(key)
  File "C:\Users\eunjo\OneDrive\바탕 화면\project\deep\venv\lib\site-packages\pandas\core\indexes\base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 1
```

**Comment by siren16** [comment]
input에 맞게 이미지 텐서를 RGB 형태로 변환

img_cv2= cv2.cvtColor(img_cv2, cv2.COLOR_BGR2RGB)
